name: build

on: push

jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go
      - name: Checkout Repository
        uses: actions/checkout@v2
      - run: go build -o app .
  docker-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - run: docker build -f dev.Dockerfile .
